# Generated by Django 2.1.1 on 2018-10-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181010_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('name',), 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='occurence_region',
            new_name='occurrence_region',
        ),
    ]
