# Generated by Django 2.1.1 on 2018-10-30 16:53

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181010_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosure',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enclosure',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enclosure',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeenclosure',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
