# Generated by Django 2.1.1 on 2018-11-06 23:07

from django.db import migrations, models
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181106_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('death_date', 'type_animal', 'name'), 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='typeanimal',
            name='icon',
            field=relativefilepathfield.fields.RelativeFilePathField(blank=True, null=True, path='/home/thejoeejoee/projects/ZIS-IIS-VUT-BIT-2017-2018/ziscz/web/static/img/icons/animals/'),
        ),
    ]
