# Generated by Django 2.1.1 on 2018-11-09 19:39

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181109_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTypeEnclosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('x_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='enclosureperson',
            name='enclosure',
        ),
        migrations.RemoveField(
            model_name='enclosureperson',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='enclosure',
            options={'ordering': ('type_enclosure__order', 'name'), 'verbose_name': 'Enclosure', 'verbose_name_plural': 'Enclosures'},
        ),
        migrations.RemoveField(
            model_name='enclosure',
            name='trained_persons',
        ),
        migrations.AddField(
            model_name='person',
            name='trained_type_animals',
            field=models.ManyToManyField(through='core.PersonTypeAnimal', to='core.TypeAnimal'),
        ),
        migrations.DeleteModel(
            name='EnclosurePerson',
        ),
        migrations.AddField(
            model_name='persontypeenclosure',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_type_enclosure_person', to='core.Person'),
        ),
        migrations.AddField(
            model_name='persontypeenclosure',
            name='type_enclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_type_enclosure_type_enclosure', to='core.TypeEnclosure'),
        ),
        migrations.AddField(
            model_name='person',
            name='trained_type_enclosures',
            field=models.ManyToManyField(through='core.PersonTypeEnclosure', to='core.TypeEnclosure'),
        ),
        migrations.AddField(
            model_name='typeenclosure',
            name='trained_persons',
            field=models.ManyToManyField(through='core.PersonTypeEnclosure', to='core.Person'),
        ),
    ]
