# Generated by Django 2.1.1 on 2018-11-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181125_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': ('date',), 'permissions': (('can_mark_own_event_as_done', 'Can mark own event as done'),)},
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ('date',), 'permissions': (('can_mark_own_event_as_done', 'Can mark own event as done'),)},
        ),
    ]
