# Generated by Django 2.1.1 on 2018-11-28 23:00

import colorful.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181125_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('-death_date', 'type_animal', 'name'), 'verbose_name': 'Zvíře', 'verbose_name_plural': 'Zvířata'},
        ),
        migrations.AlterModelOptions(
            name='animalregion',
            options={'verbose_name': 'Oblast zvířete', 'verbose_name_plural': 'Oblasti zvířete'},
        ),
        migrations.AlterModelOptions(
            name='animalstay',
            options={'ordering': ('date_from',), 'verbose_name': 'Pobyt zvířete', 'verbose_name_plural': 'Pobyty zvířete'},
        ),
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': ('date',), 'permissions': (('can_mark_own_event_as_done', 'Can mark own event as done'),), 'verbose_name': 'Čištění', 'verbose_name_plural': 'Čištění'},
        ),
        migrations.AlterModelOptions(
            name='enclosure',
            options={'ordering': ('type_enclosure__order', 'name'), 'verbose_name': 'Výběh', 'verbose_name_plural': 'Výběhy'},
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ('date',), 'permissions': (('can_mark_own_event_as_done', 'Can mark own event as done'),), 'verbose_name': 'Krmení', 'verbose_name_plural': 'Krmení'},
        ),
        migrations.AlterModelOptions(
            name='feedinganimal',
            options={'ordering': ('feeding__date', 'animal')},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('type_role__order', 'last_name', 'first_name'), 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='persontypeanimal',
            options={'verbose_name': 'Osoba vyškolená na zvíře'},
        ),
        migrations.AlterModelOptions(
            name='typeanimal',
            options={'ordering': ('order',), 'verbose_name': 'Typ zvířete', 'verbose_name_plural': 'Typy zvířat'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum úmrtí'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='occurrence_region',
            field=models.ManyToManyField(through='core.AnimalRegion', to='core.TypeRegion', verbose_name='Oblasti výskytu'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_origin_country', to='core.TypeCountry', verbose_name='Země původu'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_parent1', to='core.Animal', verbose_name='Rodič'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_parent2', to='core.Animal', verbose_name='Rodič'),
        ),
        migrations.AlterField(
            model_name='animalregion',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_region_animal', to='core.Animal'),
        ),
        migrations.AlterField(
            model_name='animalregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_region_region', to='core.TypeRegion'),
        ),
        migrations.AlterField(
            model_name='animalstay',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_stay_animal', to='core.Animal'),
        ),
        migrations.AlterField(
            model_name='animalstay',
            name='enclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_stay_enclosure', to='core.Enclosure'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateTimeField(help_text='Planned start of cleaning.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Is done?'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='enclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_enclosure', to='core.Enclosure', verbose_name='Výběh'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='executors',
            field=models.ManyToManyField(through='core.CleaningPerson', to='core.Person', verbose_name='Vykonavatelé'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0, 900), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0, 900))], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, help_text='Popisuje barvu použitou v systémovém UI jako pomocnou, černá je ve výchozím nastavení.', null=True, verbose_name='Barva'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='min_cleaners_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimální počet vykonavatelů čištění'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='min_cleaning_duration',
            field=models.DurationField(verbose_name='Minimální délka čištění'),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='amount',
            field=models.FloatField(help_text='Amount of feed.', verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='animals',
            field=models.ManyToManyField(through='core.FeedingAnimal', to='core.Animal', verbose_name='Zvířata'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateTimeField(help_text='Planned start of cleaning.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Is done?'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_executor', to='core.Person', verbose_name='Vykonavatel'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='length',
            field=models.DurationField(default=datetime.timedelta(0, 900), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0, 900))], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='type_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_feed_type', to='core.TypeFeed', verbose_name='Typy krmení'),
        ),
        migrations.AlterField(
            model_name='feedinganimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_animal_animal', to='core.Animal'),
        ),
        migrations.AlterField(
            model_name='feedinganimal',
            name='feeding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_animal_feeding', to='core.Feeding'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Vzdělání'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Přijmení'),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='person',
            name='trained_type_animals',
            field=models.ManyToManyField(blank=True, help_text='Typy zvířat, které je daná osoba vyškolena krmit.', through='core.PersonTypeAnimal', to='core.TypeAnimal', verbose_name='Kvalifikace typů zvířat'),
        ),
        migrations.AlterField(
            model_name='person',
            name='trained_type_enclosures',
            field=models.ManyToManyField(blank=True, help_text='Typy výběhů, které je osoba kvalifikována čistit.', through='core.PersonTypeEnclosure', to='core.TypeEnclosure', verbose_name='Kvalifikace typů výběhů'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_type_role', to='core.TypeRole', verbose_name='Typ role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_user', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='typeenclosure',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, help_text='Popisuje barvu použitou pro typ výběhu v systému UI jako pomocnou, černá je ve výchozím nastavení.', null=True),
        ),
    ]
